### ISSUE TITLE
这是什么原因？URL.txt不是一行一个URL吗？

### ISSUE THREAD

**Issue by UIWP0** [LHXHL/QiuPoc#1]
![image](https://github.com/LHXHL/QiuPoc/assets/32759429/fbeb5e79-5cb3-480d-a538-9bb7f55455be)

![image](https://github.com/LHXHL/QiuPoc/assets/32759429/a8a3aa2b-24fe-44ad-bdc3-84d048b28391)

**Comment by UIWP0** [comment]
没有问题了，shell.jsp文件被杀了

**Comment by UIWP0** [comment]
尴尬  :<

**Comment by LHXHL** [comment]
> 尴尬 :<

没事0.0，这是很久之前的写的了，异常处理并没有写完善，不好意思
